comment_width = 79
condense_wildcard_suffixes = true
doc_comment_code_block_width = 79
edition = "2021"
error_on_line_overflow = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
hex_literal_case = "Lower"
imports_granularity = "One"
imports_layout = "HorizontalVertical"
max_width = 79
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
short_array_element_width_threshold = 0
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
